### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by cxjacquel** [sjfricke/OpenCV-NDK#2]
Hello, 
Imposible to compile this project ; I have : 

null |  
-- | --
Build command failed. |  
Error while executing process C:\Users\AudensielTech\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\AudensielTech\Desktop\OpenCV-NDK-master\OpenCV-NDK-master\OpenCV-NDK\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=C:\Users\AudensielTech\Desktop\OpenCV-NDK-master\OpenCV-NDK-master\OpenCV-NDK\app\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=C:/Users/AudensielTech/Desktop/OpenCV-NDK-master/OpenCV-NDK-master/OpenCV-NDK/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\AudensielTech\Desktop\OpenCV-NDK-master\OpenCV-NDK-master\OpenCV-NDK\app\build\intermediates\ndkBuild\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n} |  
Android NDK: WARNING: APP_STL gnustl_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information. |  
process_begin: CreateProcess(NULL, "", ...) failed. |  
C:/Users/AudensielTech/Desktop/OpenCV-NDK-master/OpenCV-NDK-master/OpenCV-NDK |  
make: *** No rule to make target `/home/fricke/OpenCV-android-sdk/sdk/native/jni/OpenCV.mk'.  Stop. |  
Build command failed. |  
Error while executing process C:\Users\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Desktop\OpenCV-NDK-master\OpenCV-NDK-master\OpenCV-NDK\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=C:\Users\Desktop\OpenCV-NDK-master\OpenCV-NDK-master\OpenCV-NDK\app\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=C:/Users/AudensielTech/Desktop/OpenCV-NDK-master/OpenCV-NDK-master/OpenCV-NDK/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=C:\Users\Desktop\OpenCV-NDK-master\OpenCV-NDK-master\OpenCV-NDK\app\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n} |  
Android NDK: WARNING: APP_STL gnustl_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information. |  
process_begin: CreateProcess(NULL, "", ...) failed. |  
make: *** No rule to make target `/home/fricke/OpenCV-android-sdk/sdk/native/jni/OpenCV.mk'.  Stop. |  

Could you help ? 
Thx

**Comment by sjfricke** [comment]
You didn't do the 2nd step in the instructions

> Change the OpenCV Android SDK library path in [Android.mk](https://github.com/sjfricke/OpenCV-NDK/blob/master/OpenCV-NDK/app/src/main/cpp/Android.mk#L8) file to your my/path/to/OpenCV-android-sdk/sdk/native/jni/OpenCV.mk

You need to download the [OpenCV Android SDK](https://sourceforge.net/projects/opencvlibrary/files/opencv-android/) (which was too big to track in this repo) and then change that line from

`/home/fricke/OpenCV-android-sdk/sdk/native/jni/OpenCV.mk`
which was my personal path to the path for you where you have it on your machine

ALSO looks like you are on windows so **MAKE SURE** you either do `/` for the slashes in the path inside that Android.mk file

**Comment by sjfricke** [comment]
Assuming you got it to work, if not please comment and will reopen
